### ISSUE TITLE
complex order numbers are broken in index.xml

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#108]
Say, `0.24-test` will produce `order="0"`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#108` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2685](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.1`

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 2440d1a 2017-08-30T14:59:31
IllegalStateException: java.lang.reflect.InvocationTargetException
java.lang.IllegalStateException: Failed to acquire "2017/01/C3NDPUA8L/elections.xml" in 20s
	at com.zerocracy.farm.sync.SyncItem.acquire(SyncItem.java:92)
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:133)
	at com.zerocracy.farm.StrictProject.acq(StrictProject.java:107)
	at com.zerocracy.farm.UplinkedProject.lambda$acq$4(UplinkedProject.java:98)
	at org.cactoos.scalar.Ternary.value(Ternary.java:118)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.pm.staff.Elections.item(Elections.java:264)
	at com.zerocracy.pm.staff.Elections.bootstrap(Elections.java:67)
	at com.zerocracy.pm.staff.Elections$bootstrap.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
...
```

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#108` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2715](http://www.0crat.com/u/yegor256).
