### ISSUE TITLE
XML upgrades validation

### ISSUE THREAD

**Issue by g4s8** [zerocracy/datum#115]
We need to validate XML upgrades to avoid issues like in #105 PR.
I think we can write some tests for upgrades and start them from `Rakefile`. It may be target xml file which will be upgraded and and simple script with xpath assertions. We can place them in directories named as upgrade version.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#115` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+1530](http://www.0crat.com/u/g4s8).

**Comment by yegor256** [comment]
@g4s8 we have that test already, see: https://github.com/zerocracy/datum/blob/master/Rakefile#L60-L65 The problem in #105 was that `simple.xml` didn't have cases of projects without titles. I fixed that in 99d5645

**Comment by g4s8** [comment]
@yegor256 thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalStateException: event of type 'closed' not found in issue #115
	at com.jcabi.github.Issue$Smart.latestEvent_aroundBody40(Issue.java:365)
	at com.jcabi.github.Issue$Smart$AjcClosure41.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.latestEvent(Issue.java:354)
	at com.zerocracy.radars.github.RbVerifyCloser.closer(RbVerifyCloser.java:83)
	at com.zerocracy.radars.github.RbVerifyCloser.react(RbVerifyCloser.java:47)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(R... 
```

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#115` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4185](http://www.0crat.com/u/yegor256).
