### ISSUE TITLE
[Telegram] Unable to change the rate

### ISSUE THREAD

**Issue by kkamkou** [zerocracy/datum#116]
By typing one of them, the reply is `Your rate is 0.`:
 - `rate $20`
 - `rate 20`

By typing `rate=20`, the result is `Can't understand "rate=20"`.

Please also provide the format of the command in #104

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
How you are do it? 0crat not ask me over telegram...

**Comment by kkamkou** [comment]
Delete the bot and chat it again.

**Comment by DronMDF** [comment]
@kkamkou No answer...
![image](https://user-images.githubusercontent.com/2982959/30534754-3ec44254-9c68-11e7-9882-71b2ccc43d0a.png)

Where am I wrong?

**Comment by kkamkou** [comment]
It replies after 2+ minutes in my case. I'm not sure if it works ^^.

**Comment by yegor256** [comment]
@kkamkou replies perfectly OK to me now... can you please check again?

**Comment by DronMDF** [comment]
@yegor256 How does the zerocrat understand that I am in a telegram, this is DronMDF from the github?

![image](https://user-images.githubusercontent.com/2982959/30586651-55061f52-9d39-11e7-8c11-56d4fefecb95.png)

No answer.

**Comment by yegor256** [comment]
@DronMDF hm. replies to me immediately now.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: issue #116 doesn't have an assignee, use hasAssignee()
	at com.jcabi.github.Issue$Smart.assignee_aroundBody24(Issue.java:254)
	at com.jcabi.github.Issue$Smart$AjcClosure25.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.assignee(Issue.java:253)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:44)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.jav...
```

**Comment by DronMDF** [comment]
@yegor256 What command should I give to the telegram zerocrat?

**Comment by kkamkou** [comment]
@yegor256 yes, the speed of response is recovered.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#116` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by g4s8** [comment]
@kkamkou @DronMDF change rate command format is `rate set <value>`. 
For instance: `rate set $100`.
But this command is broken at the moment. It should be fixed soon with #84

**Comment by kkamkou** [comment]
duplicates #84

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#116` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @g4s8, total is [+1710](http://www.0crat.com/u/g4s8).
