### ISSUE TITLE
JsonObject -> JsonString ClassCastException

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#117]
At some point, 0crat tries to perform
```
JsonObject.getString("key")
```
Trouble is, "key" points to a JsonObject, not to a String.
See here:
https://github.com/yegor256/0pdd/issues/109#issuecomment-329703923

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: issue #117 doesn't have an assignee, use hasAssignee()
	at com.jcabi.github.Issue$Smart.assignee_aroundBody24(Issue.java:254)
	at com.jcabi.github.Issue$Smart$AjcClosure25.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.assignee(Issue.java:253)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:44)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.jav...
```

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#117` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by filfreire** [comment]
@yegor256 @g4s8 saw this happening also in 
https://github.com/yegor256/tacit/issues/99
and in https://github.com/yegor256/cactoos/issues/437

**Comment by g4s8** [comment]
@yegor256 @amihaiemil @filfreire It was an issue with github webhook's labels parsing, should be fixed with zerocracy/farm#309

**Comment by amihaiemil** [comment]
Then I'm closing this :)

**Comment by 0crat** [comment]
Oops! There is an open order for this job, @g4s8 is still working with it.

**Comment by g4s8** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/zerocracy/datum/issues/117#issuecomment-338410880))

@g4s8 @g4s8 resigned from `gh:zerocracy/datum#117`, please stop working.
