### ISSUE TITLE
0crat roles failure

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#121]
Internal application error

0.16.1, 4ccd020

Please, report it here. We will do our best to fix it as soon as possible. We're very sorry.

java.lang.IllegalStateException: [GET http://www.0crat.com/a/C6KLDT6QG?a=pm%2Fstaff%2Froles] failed in 20s: java.lang.IllegalStateException: Failed to acquire "PMO/people.xml" in 20s
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
	at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:199)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
	at org.takes.rs.RsPrint.print(RsPrint.java:114)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
0crat assign failed with same reason.

**Comment by DronMDF** [comment]
Problem still here.
https://github.com/DronMDF/telebot/issues/7
I look this in different places.

**Comment by DronMDF** [comment]
Failed to acquire "PMO/people.xml"
Was going out.
I can assign roles.

New bug:
Failed to acquire "PMO/claims.xml" in 20s

**Comment by DronMDF** [comment]
https://github.com/DronMDF/telebot/issues/6#issuecomment-333118737
Failed to acquire "PMO/people.xml" again.

**Comment by yegor256** [comment]
@DronMDF I belive it's fixed already, please try again

**Comment by DronMDF** [comment]
I do not see the problem now.
It fixed.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#121` was not in scope
