### ISSUE TITLE
Severall issues with roles.xml, claims.xml and orders.xml

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#139]
On https://github.com/yegor256/rultor/issues/1219
and on https://github.com/yegor256/rultor/issues/1218

we're seeing a lot of defect comments made by @0crat

* roles.xml (1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13)
```
  java.io.IOException: java.lang.IllegalStateException: Failed to acquire "roles.xml" in "C3SAYRPH9" in 30s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.staff.Roles.item(Roles.java:258)
	at com.zerocracy.pm.staff.Roles.bootstrap(Roles.java:59)
	at com.zerocracy.radars.github.RbPingArchitect.react(RbPingArchitect.java:49)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at o... 
```

* claims.xml (1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13)
```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

* orders.xml (1.0-SNAPSHOT 85e7bf1 2017-10-23T11:13:49)
```
 java.io.UncheckedIOException: java.io.IOException: java.lang.IllegalStateException: The order for job "gh:yegor256/rultor#1205" exists in orders.xml, but the job is absent in the WBS among 8 jobs.
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:60)
	at com.zerocracy.farm.ruled.RdRules.validate(RdRules.java:107)
	at com.zerocracy.farm.ruled.RdItem.close(RdItem.java:143)
	at com.zerocracy.pm.staff.Roles.bootstrap(Roles.java:61)
	at com.zerocracy.radars.github.RbPingArchitect.react(RbPingArchitect.java:49)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)... 
```

@yegor256 FYI

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire I believe it's fixed now, let's close this one. It's closed in a private repo, can't link it here.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
com.mongodb.MongoInterruptedException: Interrupted while waiting for a server that matches WritableServerSelector
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:124)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getWriteConnectionSource(ClusterBinding.java:68)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:168)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:74)
	at com.mongodb.Mongo.execute(Mongo.java:819)
	at com.mongodb.Mongo$2.execute(Mongo.java:802)
	at com.mongodb.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:550)
	at com.mongodb.MongoCollectionImpl.insertOne(MongoCollectionImpl.j...
```

My version: `1.0-SNAPSHOT`, `4583691`, `2017-10-24T15:25:29` /cc @yegor256

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#139`.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#139`.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
com.mongodb.MongoInterruptedException: Interrupted acquiring a permit to retrieve an item from the pool 
	at com.mongodb.internal.connection.ConcurrentPool.acquirePermit(ConcurrentPool.java:186)
	at com.mongodb.internal.connection.ConcurrentPool.get(ConcurrentPool.java:126)
	at com.mongodb.internal.connection.ConcurrentPool.get(ConcurrentPool.java:109)
	at com.mongodb.internal.connection.PowerOfTwoBufferPool.getBuffer(PowerOfTwoBufferPool.java:76)
	at com.mongodb.connection.SocketStream.read(SocketStream.java:80)
	at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:486)
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:210)
	at com.mongodb.connection.CommandHelper.receiveReply(CommandHelper.java:134)
	at com.mongodb.connection.CommandHelper.receiveCommandDocument(CommandHelper.java:130)
	at com.mongodb.connection.CommandHelper.executeCommandWithoutCheckingForFailure(CommandHelper.java:...
```

My version: `1.0-SNAPSHOT`, `4583691`, `2017-10-24T15:25:29` /cc @yegor256

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#139`.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#139`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#139` is not in scope.
