### ISSUE TITLE
Case sensetivity github names in assign command

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#143]
![image](https://user-images.githubusercontent.com/2982959/32702824-8a26a44c-c7fd-11e7-9f7a-f6235ab1ab30.png)

I cannot assign rove over real GH name, I need use lowercase.

This is related to #78

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF I believe it's fixed, please try again

**Comment by DronMDF** [comment]
Yes, this is closed.
Thank's.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't add, claims overflow in C3NDPUA8L, too many items: 41
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:84)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:169)
	at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
	...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256
