### ISSUE TITLE
IllegalArgumentException - can't process this type of notification

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#147]
Getting hundreds of these notifications across projects (rultor, cactoos, ...)

```
java.lang.IllegalArgumentException: Can't process this type of notification: {"title":"#354 ignore @0crat assignments","url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","latest_comment_url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","type":"Commit"}
	at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:103)
	at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
	at com.zerocracy.radars.github.Reaction$Chain.react(Reaction.java:74)
	at com.zerocracy.radars.github.ReLogged.react(ReLogged.java:55)
	at com.zerocracy.radars.github.RbOnComment.react(RbOnComment.java:60)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos...
```

Example: https://github.com/yegor256/cactoos/issues/486#issuecomment-349859401

**Comment by yegor256** [comment]
@filfreire fixed, thanks for reporting!
