### ISSUE TITLE
0crat returns OutOfMemoryError

### ISSUE THREAD

**Issue by romach** [zerocracy/datum#195]
When I open http://www.0crat.com/ the error is returned:

```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1367)
	at io.sentry.connection.AsyncConnection.send(AsyncConnection.java:93)
	at io.sentry.SentryClient.sendEvent(SentryClient.java:134)
	at io.sentry.SentryClient.sendEvent(SentryClient.java:175)
	at io.sentry.SentryClient.sendException(SentryClient.java:202)
	at io.sentry.Sentry.capture(Sentry.java:156)
	at com.zerocracy.tk.TkApp.lambda$new$3(TkApp.java:241)
	at org.takes.facets.fallback.FbChain$1.route(FbChain.java:71)
	at org.takes.facets.fallback.FbWrap.route(FbWrap.java:59)
	at org.takes.facets.fallback.TkFallback$2.head(TkFallback.java:170)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.rs.RsPrint.printHead(RsPrint.java:128)
	at org.takes.rs.RsPrint.print(RsPrint.java:113)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.zerocracy.farm.sync.Terminator.submit(Terminator.java:106)
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:97)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:117)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.app...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by allanws** [comment]
It's happening [here](https://github.com/yegor256/cactoos/issues/541#issuecomment-356392880) as well.

**Comment by yegor256** [comment]
@romach it's a temporary issue, we will fix it soon

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#195` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#195](https://github.com/zerocracy/datum/issues/195) was not in scope
