### ISSUE TITLE
OOM when applying

### ISSUE THREAD

**Issue by Sammers21** [zerocracy/datum#196]
Steps to reporoduce:

1. send `apply`

Observer behavior: There is an unrecoverable failure on my side. Please, submit it here:
```text
java.lang.OutOfMemoryError: unable to create new native thread
 at java.lang.Thread.start0(Native Method)
 at java.lang.Thread.start(Thread.java:717)
 at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:112)
 at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:96)
 at java.security.AccessController.doPrivileged(Native Method)
 at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:95)
 at sun.net.www.http.HttpClient.putInKeepAliveCache(HttpClient.java:438)
 at sun.net.www.http.HttpClient.finished(HttpClient.java:395)
 at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:97)
 at sun.net.www.MeteredStream.justRead(MeteredStream.java:93)
 at sun.net.www.MeteredStream.read(MeteredStream.java:135)
 at java.io.FilterInputStream.read(FilterInputStream.java:133)
 at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
 at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManag...
```

1.0-SNAPSHOT /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: BkParallel-0 interrupted while waiting for "roles.xml" in C3NDPUA8L for 55s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:117)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@Sammers21 thanks, it's a temporary issue, we will work on this

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#196` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#196](https://github.com/zerocracy/datum/issues/196) was not in scope
