### ISSUE TITLE
telegram bot answers with exception when hello

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#207]
I tried to say `hello` to telegram bot and got this:

> com.amazonaws.SdkClientException: Unable to execute HTTP request: null
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
 at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
 at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
 at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
 at com...

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by t-izbassar** [comment]
Well, it's works now. Some flicker with amazon s3?

**Comment by yegor256** [comment]
@t-izbassar  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#207` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#207](https://github.com/zerocracy/datum/issues/207) was not in scope
