### ISSUE TITLE
0crat telegram bot doesn't accepting new apply

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#218]
When I submit a new apply to 0crat telegram bot, usina the command `apply ID 10` or `apply ID $10` I get this message:
```
Argument "10" doesn't match regex "$\d{1,3}"

Remember, this chat is for managing your personal profile; to manage a project, please open or create a new Slack channel and invite the bot there.
```

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx thanks, fixed!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#218` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#218](https://github.com/zerocracy/datum/issues/218) was not in scope

**Comment by fabriciofx** [comment]
@yegor256 This issue wasn't closed. Look:

```
apply C7JGJ00DP $10

I can't do it for technical reasons, I'm very sorry.  If you don't know what to do,  submit this error as a ticket  here (https://github.com/zerocracy/datum):

 1.0-SNAPSHOT 5d0c73b6 2018-01-15T21:41:58
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pmo/profile/apply_to_project.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pmo/profile/apply_to_project.groovy
 at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
 at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
 at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
 at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
 at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
 at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
 at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
 at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
 at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
 at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
 at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
 at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
 at org.cactoos.func.UncheckedFunc.lambda$apply$0(Unchec... 
```

**Comment by yegor256** [comment]
@fabriciofx should be fine now, please try

**Comment by flslkxtc** [comment]
I'm still encountering this issue today. Telegram bot does react to all messages, but  `apply PROJECTID 0` or `apply PROJECTID 0$` commands both are ending up with `Argument "0" doesn't match regex \$\d{1,3}` response.

**Comment by fabriciofx** [comment]
@flslkxtc Try `apply PROJECT ID $0`.

**Comment by flslkxtc** [comment]
@fabriciofx thank you, that one was on me.

**Comment by fabriciofx** [comment]
@flslkxtc You're welcome!
