### ISSUE TITLE
more types of claims

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#23]

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#23` is not in scope

**Comment by yegor256** [comment]
@0crat in

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side.
Please, email this to bug@0crat.com:

```
java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: cvc-complex-type.2.4.a: Invalid content was found starting with element 'claim'. One of '{type}' is expected.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:110)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:83)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:74)
	at com.zerocracy.Xocument.modify(Xocument.java:168)
	at com.zerocracy.pm.Claims.add(Claims.java:84)
	at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:55)
	at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:58)
	at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:55)
	at com.zerocracy.radars.github.ReSafe.react(ReSafe.java:57)
	at com.zerocracy.radars.github.ReOnComment.send(ReOnComment.java:191)
	at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:114)
	at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
	at com.zerocracy.radars.github.Reaction$Chain.react(Reaction.java:7...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side.
Please, email this to bug@0crat.com:

```
java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: cvc-complex-type.2.4.a: Invalid content was found starting with element 'claim'. One of '{type}' is expected.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:110)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:83)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:74)
	at com.zerocracy.Xocument.modify(Xocument.java:168)
	at com.zerocracy.pm.Claims.add(Claims.java:84)
	at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:55)
	at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:58)
	at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:55)
	at com.zerocracy.radars.github.ReSafe.react(ReSafe.java:57)
	at com.zerocracy.radars.github.ReOnComment.send(ReOnComment.java:191)
	at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:114)
	at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
	at com.zerocracy.radars.github.Reaction$Chain.react(Reaction.java:7...
```
