### ISSUE TITLE
Exception when acquiring a status of issue

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#259]
See [here](https://github.com/yegor256/jpeek/issues/17).

> java.lang.IllegalStateException: thread 'BkParallel-5' in group 'main' interrupted
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:184)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Comment$Smart.issue(Comment.java:181)
	at com.zerocracy.radars.github.ReSafe.lambda$react$1(ReSafe.java:70)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:90)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at com.zerocracy.radars.github.ReSafe.react(ReSafe.java:80)
	at com.zerocracy.radars.github.ReOnComment.send(...

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral it was a temporary issue, thanks for reporting

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#259` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#259](https://github.com/zerocracy/datum/issues/259) was not in scope
