### ISSUE TITLE
mentor for everybody in people.xsd

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#38]

**Comment by yegor256** [comment]
@rultor release, tag is `0.22`

**Comment by yegor256** [comment]
@rultor release, tag is `0.22`

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#38` was not in scope

**Comment by alex-palevsky** [comment]
@0crat hello

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: com.zerocracy.jstk.SoftException: You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only
	at com.zerocracy.radars.github.Author.toString(Author.java:63)
	at org.xembly.Directives.set(Directives.java:416)
	at com.zerocracy.pm.ClaimOut.author(ClaimOut.java:121)
	at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:54)
	at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:58)
	at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:55)
	at com.zerocracy.radars.github.ReSafe.react(ReSafe.java:57)
	at com.zerocracy.radars.github.ReOnComment.send(ReOnComment.java:195)
	at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:115)
	at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
	at com.zerocracy.radars.github.Reaction$Chain.react(Reaction.java:74)
	at com.zerocracy.radars.github.ReLogged.react(ReLogged.java:55)
	at com.zerocracy.radars.github.GithubFetch.fetch(Gi...
```
