### ISSUE TITLE
0crat fails on links command

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#69]
![image](https://user-images.githubusercontent.com/6305156/29156596-6cdbc170-7dab-11e7-9674-0e6f69b4688a.png)

Here is the exception:

```
1.0-SNAPSHOT ${buildNumber} 2017-08-09T16:29:37
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
    at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
    at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
    at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
    at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:197)
    at com.zerocracy.farm.reactive.RunnableWithTrigger.run(RunnableWithTrigger.java:52)
    at java....
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil thanks for reporting, we're on it...

**Comment by DronMDF** [comment]
links is work in next syntax:
$0crat links add github user/repo
I can link repo. :)

**Comment by amihaiemil** [comment]
@DronMDF Yes, but even so, are we supposed, as DEV roles, to be able to link and bootstrap?

**Comment by yegor256** [comment]
@amihaiemil is it still an issue?

**Comment by amihaiemil** [comment]
@yegor256 I don't know, you must invite me again, 0crat forgot me :(

**Comment by yegor256** [comment]
@amihaiemil done

**Comment by amihaiemil** [comment]
@yegor256 yes, it seems to be fixed:

![screenshot_2017-10-20-14-36-05](https://user-images.githubusercontent.com/6305156/31819169-250b067c-b5a4-11e7-977e-f410d93a15a3.jpg)

Closing this.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#69`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#69` is not in scope.

**Comment by amihaiemil** [comment]
@yegor256 I have to say, that "Oops" is rather annoying :)))

**Comment by yegor256** [comment]
@amihaiemil we'll think about that "oops" thing ) thanks!
