### ISSUE TITLE
0crat doesn't seem to understand DEV commands

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#70]
![image](https://user-images.githubusercontent.com/6305156/29156638-a7ab865a-7dab-11e7-8a78-fa8199c5a1f4.png)

It doesn't understand "skills" and it tells me about the "bootstrap" command, which is for PO, not for DEV role.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil thanks for reporting, let us check...

**Comment by yegor256** [comment]
@amihaiemil try again please

**Comment by amihaiemil** [comment]
@yegor256 it's the same :(

**Comment by yegor256** [comment]
@amihaiemil it has to be the same, but now it explains what's going on. You should be talking in a private chat with the bot.

**Comment by amihaiemil** [comment]
Yes, private chat, still the exception :D

**Comment by yegor256** [comment]
@amihaiemil can you show the screenshot?

**Comment by amihaiemil** [comment]
![screenshot_2017-08-10-19-59-38](https://user-images.githubusercontent.com/6305156/29182178-920e9ac0-7e06-11e7-8f89-09e590f92ec7.jpg)

@yegor256 now it works, no stacktrace, but it is a private chat and I think it should suggest commands for DEV not for OP

**Comment by yegor256** [comment]
@amihaiemil it's not a private chat, it's a channel. You should start a private conversation with the bot.

**Comment by amihaiemil** [comment]
![screenshot_2017-08-10-20-07-09](https://user-images.githubusercontent.com/6305156/29182425-8d5e2fc6-7e07-11e7-8a75-5ff087116d2a.jpg)

@yegor256 tried direct chat, I get an exception, I suppose because I have no registered skills. What's the syntax for registering?

**Comment by yegor256** [comment]
@amihaiemil it was a bug, try now pls

**Comment by amihaiemil** [comment]
@yegor256 ok, works, it says "Your skills are not defined yet". How do I define them?

**Comment by yegor256** [comment]
@amihaiemil we decided to remove skills at all. No need to define them. Let's close this.

**Comment by amihaiemil** [comment]
Ok, closing

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-08-10T18:35:57
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:zerocracy/datum#70` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$1.call(Unknown Source)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.re...
```
