### ISSUE TITLE
'Hello' and 'skills' fail on GIthub repo which 0crat doesn't know

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#71]
I said 'hello' and 'skills' to 0crat, in one of my repos, and it replied with an exception:

![image](https://user-images.githubusercontent.com/6305156/29156717-fcc91d32-7dab-11e7-9a4a-8eb3d6ecb001.png)

```
java.lang.IllegalStateException: Can't find anything with links/link[@rel='github' and @href='opencharles/charles-rest']
	at com.zerocracy.farm.S3Farm.force(S3Farm.java:107)
	at com.zerocracy.farm.S3Farm.find(S3Farm.java:87)
	at com.zerocracy.farm.sync.SyncFarm.find(SyncFarm.java:60)
	at com.zerocracy.farm.SmartFarm.lambda$value$1(SmartFarm.java:83)
	at com.zerocracy.farm.reactive.RvFarm.find(RvFarm.java:67)
	at com.zerocracy.radars.github.GhProject.project(GhProject.java:90)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:60)
	at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:58)
	at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:55)
	at com.zerocracy.radars.github.ReSafe.lambda$react$0(ReSafe.java:61)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:...
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil thanks, we'll take a look right now

**Comment by yegor256** [comment]
@amihaiemil try again please

**Comment by amihaiemil** [comment]
@yegor256 this seems to work. It tells me the project is not managed and sends me to Slack

**Comment by yegor256** [comment]
@amihaiemil that's how it should be. See http://datum.zerocracy.com/pages/policy.html#11

**Comment by amihaiemil** [comment]
Ok :D

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-08-10T15:46:37
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:zerocracy/datum#71` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reacti...
```
