### ISSUE TITLE
0crat.com can't find user

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#72]
![image](https://user-images.githubusercontent.com/2982959/29164259-83b25280-7dc7-11e7-8089-c11af353d79e.png)

The error occurs after clicking on the username at the bottom of the page.
This can be due to aliases.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
http://www.0crat.com/u/dronmdf is work ok.

**Comment by yegor256** [comment]
@DronMDF fixed, thanks for reporting!

**Comment by DronMDF** [comment]
Thank's.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-08-10T15:46:37
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:zerocracy/datum#72` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reacti...
```
