### ISSUE TITLE
0crat.com not show wbs for my project.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#74]
www.0crat.com/a/C6KLDT6QG?a=pm/scope/wbs

```
java.lang.IllegalStateException: [GET http://www.0crat.com/a/C6KLDT6QG?a=pm%2Fscope%2Fwbs] failed in 20s: java.lang.IllegalStateException: Failed to acquire "2017/08/C6KLDT6QG/wbs.xml" in 20s
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
	at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:199)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
	at org.takes.rs.RsPrint.print(RsPrint.java:114)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/08/C6KLDT6QG/wbs.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.tk.XeXsl.toXembly(XeXsl.java:71)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:74)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.RsXembly.render(RsXembly.java:147)
	at org.takes.rs.xe.RsXembly.access$000(RsXembly.java:65)
	at org.takes.rs.xe.RsXembly$1.body(RsXembly.java:129)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithoutHeader$1.body(RsWithoutHeader.java:75)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsXslt$1.body(RsXslt.java:113)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:116)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsGzip.make(RsGzip.java:87)
	at org.takes.rs.RsGzip.body(RsGzip.java:76)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
	... 12 more
Caused by: java.lang.IllegalStateException: Failed to acquire "2017/08/C6KLDT6QG/wbs.xml" in 20s
	at com.zerocracy.farm.sync.SyncItem.acquire(SyncItem.java:92)
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:134)
	at com.zerocracy.farm.StrictProject.acq(StrictProject.java:107)
	at com.zerocracy.farm.UplinkedProject.lambda$acq$4(UplinkedProject.java:98)
	at org.cactoos.scalar.Ternary.value(Ternary.java:118)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	... 54 more
```

commans $0crat wbs not worked too.

![image](https://user-images.githubusercontent.com/2982959/29168094-1cc0ca5c-7dd6-11e7-9c42-c9debde50830.png)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
I can view wbs over web.
Thank's.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 1cbcae0 2017-08-11T07:54:51
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:zerocracy/datum#74` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reacti...
```
