### ISSUE TITLE
$0crat call me on github by slack name...

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#75]
https://github.com/DronMDF/telebot/issues/4

On github i known as DronMDF

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
Sorry, I had to invite by github name.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-08-10T14:51:06
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:zerocracy/datum#75` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$1.call(Unknown Source)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.re...
```
