### ISSUE TITLE
Case sensetivity names

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#78]
I am a @DronMDF

I assign ARC roles to myself.
![image](https://user-images.githubusercontent.com/2982959/29178465-505344c0-7dfa-11e7-8dd3-1e029a39a18f.png)

0crat not remember name case, and call me @dronmdf. This is not work on github.
https://github.com/DronMDF/telebot/issues/1

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
related to #72

**Comment by yegor256** [comment]
@DronMDF is it still an issue?

**Comment by DronMDF** [comment]
@yegor256 Yes, this is a work. 0crat call me right.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalStateException: event of type 'closed' not found in issue #78
	at com.jcabi.github.Issue$Smart.latestEvent_aroundBody40(Issue.java:365)
	at com.jcabi.github.Issue$Smart$AjcClosure41.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.latestEvent(Issue.java:354)
	at com.zerocracy.radars.github.RbVerifyCloser.closer(RbVerifyCloser.java:83)
	at com.zerocracy.radars.github.RbVerifyCloser.react(RbVerifyCloser.java:47)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Re... 
```

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#78`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#78` is not in scope.
