### ISSUE TITLE
Resign command cause exception

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#93]
![image](https://user-images.githubusercontent.com/2982959/29409257-184c6732-8354-11e7-9815-685bf6f08625.png)

This is a slack name.
I need to use gh name in assign? Right?
Resigning is complete, user leave roles.

Details:
1.0-SNAPSHOT 2f52b52 2017-08-17T05:56:32
IllegalStateException: java.lang.reflect.InvocationTargetException
java.io.FileNotFoundException: /tmp/5833513183822423056/PMO/projects/tanyaerm.xml (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at org.cactoos.io.InputOf.lambda$new$2(InputOf.java:81)
    at org.cactoos.io.InputOf.stream(InputOf.java:315)
    at org.cactoos.io.TeeInput.stream(TeeInput.java:870)
    at org.cactoos.io.InputAsBytes.asBytes(InputAsBytes.java:79)
    at org.cactoos.io.BytesOf.asBytes(BytesOf.java:290)
    at org.cactoos.text.TextOf.lambda$new$0(TextOf.java:224)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
    at org.cactoos.text.TextOf.asString(TextOf.java:267)
    at org.cactoos.text.UncheckedText.asString(UncheckedText.java:90)
    at com.zerocracy.Xocument.toString(Xocument.java:114)
    at com.zerocracy.Xocument.modify(Xocument.java:199)
    at com.zerocracy.p...

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#93` assigned to @carlosmiranda, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@carlosmiranda resigned from `gh:zerocracy/datum#93`, please stop working.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#93` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@DronMDF do you still see this problem?

**Comment by DronMDF** [comment]
@yegor256 This is ok now. Thank's

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#93` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @caarlos0, total is [+585](http://www.0crat.com/u/caarlos0).
